with-expecter: true
boilerplate-file: ".mockery_boilerplate.txt"
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
resolve-type-alias: False
issue-845-fix: True

packages:
  github.com/MoMentalochka/HomeWork/payment/internal/service:
    config:
      include-regex: ".*Service"

  github.com/MoMentalochka/HomeWork/inventory/internal/service:
    config:
      include-regex: ".*Service"

  github.com/MoMentalochka/HomeWork/inventory/internal/repository:
    config:
      include-regex: ".*Repository"
