syntax = "proto3";

package inventory.v1;

import "google/protobuf/timestamp.proto";
//import "google/protobuf/wrappers.proto";
//import "google/protobuf/empty.proto";

option go_package = "github.com/MoMentalochka/HomeWork/inventory/pkg/proto/inventory/v1;inventory_v1";

// InventoryService
service InventoryService {
//  GetPart
  rpc GetPart(GetPartRequest) returns (GetPartResponse);
//ListParts
  rpc ListParts(ListPartsRequest) returns (ListPartsResponse);
}
// GetPartRequest
message GetPartRequest {
  //
  string uuid = 1;
}
// GetPartResponse
message GetPartResponse {
  //
  Part part = 1;
}
// ListPartsRequest
message ListPartsRequest {
  //  Фильтр по деталям (все поля опциональны)
  PartsFilter filter = 1;
}
// ListPartsResponse
message ListPartsResponse {
  //  Список найденных деталей
  repeated Part parts = 1;
}

// PartsFilter
message PartsFilter {
  //  Список UUID. Пусто — не фильтруем по UUID
  repeated string uuids = 1;

  //  Список имён. Пусто — не фильтруем по имени
  repeated string names = 2;

  //  Список категорий. Пусто — не фильтруем по категории
  repeated Category categories = 3;

  //  Список стран производителей. Пусто — не фильтруем по стране
  repeated string manufacturer_countries = 4;

  //  Список тегов. Пусто — не фильтруем по тегам
  repeated string tags = 5;
}

// Part
message Part {
  //  Уникальный идентификатор детали
  string uuid = 1;
  //  Название детали
  string name = 2;
  //  	Описание детали
  string description = 3;
  //  Цена за единицу
  double price = 4;
  //  Количество на складе
  int64 stock_quantity = 5;
  //  Категория
  Category category = 6;
  //  Размеры детали
  Dimensions dimensions = 7;
  //  Информация о производителе
  Manufacturer manufacturer = 8;
  //  Теги для быстрого поиска
  repeated string tags	 = 9;
  //  Гибкие метаданные
  map<string, Value> metadata = 10;
  //  Дата создания
  google.protobuf.Timestamp created_at = 11;
  //  	Дата обновления
  google.protobuf.Timestamp updated_at = 12;
}

// Category
enum Category {
  //	Неизвестная категория
  CATEGORY_UNKNOWN_UNSPECIFIED = 0;
  //  Двигатель
  CATEGORY_ENGINE = 1;
  //  Топливо
  CATEGORY_FUEL = 2;
  //  Иллюминатор
  CATEGORY_PORTHOLE = 3;
  //  Крыло
  CATEGORY_WING = 4;
}

// Dimensions
message Dimensions {
  //  Длина в см
  double length = 1;
  //  Ширина  в см
  double width =  2;
  //  о в см
  double height = 3;
  //  Вес в кг
  double weight = 4;
}

// Manufacturer
message Manufacturer {
  //  Название
  string name = 1;
    //  Название
  string country = 2;
    //  Название
  string website = 3;
}

// Value
message Value {
  oneof value {
    string string_value = 1;
    int64 int64_value = 2;
    double double_value = 3;
    bool bool_value = 4;
  }
}