// Custom mockery prefix
// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	model "github.com/MoMentalochka/HomeWork/order/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

type OrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderRepository) EXPECT() *OrderRepository_Expecter {
	return &OrderRepository_Expecter{mock: &_m.Mock}
}

// AddOrder provides a mock function with given fields: order
func (_m *OrderRepository) AddOrder(order *model.OrderDto) {
	_m.Called(order)
}

// OrderRepository_AddOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddOrder'
type OrderRepository_AddOrder_Call struct {
	*mock.Call
}

// AddOrder is a helper method to define mock.On call
//   - order *model.OrderDto
func (_e *OrderRepository_Expecter) AddOrder(order interface{}) *OrderRepository_AddOrder_Call {
	return &OrderRepository_AddOrder_Call{Call: _e.mock.On("AddOrder", order)}
}

func (_c *OrderRepository_AddOrder_Call) Run(run func(order *model.OrderDto)) *OrderRepository_AddOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.OrderDto))
	})
	return _c
}

func (_c *OrderRepository_AddOrder_Call) Return() *OrderRepository_AddOrder_Call {
	_c.Call.Return()
	return _c
}

func (_c *OrderRepository_AddOrder_Call) RunAndReturn(run func(*model.OrderDto)) *OrderRepository_AddOrder_Call {
	_c.Run(run)
	return _c
}

// GetOrder provides a mock function with given fields: id
func (_m *OrderRepository) GetOrder(id string) *model.OrderDto {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *model.OrderDto
	if rf, ok := ret.Get(0).(func(string) *model.OrderDto); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OrderDto)
		}
	}

	return r0
}

// OrderRepository_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type OrderRepository_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - id string
func (_e *OrderRepository_Expecter) GetOrder(id interface{}) *OrderRepository_GetOrder_Call {
	return &OrderRepository_GetOrder_Call{Call: _e.mock.On("GetOrder", id)}
}

func (_c *OrderRepository_GetOrder_Call) Run(run func(id string)) *OrderRepository_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *OrderRepository_GetOrder_Call) Return(_a0 *model.OrderDto) *OrderRepository_GetOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepository_GetOrder_Call) RunAndReturn(run func(string) *model.OrderDto) *OrderRepository_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
