// Code generated by ogen, DO NOT EDIT.

package orders_v1

import (
	"github.com/go-faster/errors"
)

// Ref: #/components/schemas/conflict
type Conflict struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *Conflict) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Conflict) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Conflict) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Conflict) SetMessage(val string) {
	s.Message = val
}

func (*Conflict) orderCancelRes() {}
func (*Conflict) orderPayRes()    {}

// Ref: #/components/schemas/create_order_request
type CreateOrderRequest struct {
	// User ID.
	UserUUID string `json:"user_uuid"`
	// Parts ID array.
	PartUuids []string `json:"part_uuids"`
}

// GetUserUUID returns the value of UserUUID.
func (s *CreateOrderRequest) GetUserUUID() string {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *CreateOrderRequest) GetPartUuids() []string {
	return s.PartUuids
}

// SetUserUUID sets the value of UserUUID.
func (s *CreateOrderRequest) SetUserUUID(val string) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *CreateOrderRequest) SetPartUuids(val []string) {
	s.PartUuids = val
}

// Ref: #/components/schemas/create_order_response
type CreateOrderResponse struct {
	// Order ID.
	OrderUUID string `json:"order_uuid"`
	// Total Price.
	TotalPrice float64 `json:"total_price"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *CreateOrderResponse) GetOrderUUID() string {
	return s.OrderUUID
}

// GetTotalPrice returns the value of TotalPrice.
func (s *CreateOrderResponse) GetTotalPrice() float64 {
	return s.TotalPrice
}

// SetOrderUUID sets the value of OrderUUID.
func (s *CreateOrderResponse) SetOrderUUID(val string) {
	s.OrderUUID = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *CreateOrderResponse) SetTotalPrice(val float64) {
	s.TotalPrice = val
}

// Ref: #/components/schemas/not_found
type NotFound struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *NotFound) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *NotFound) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *NotFound) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *NotFound) SetMessage(val string) {
	s.Message = val
}

func (*NotFound) getOrderByIdRes() {}
func (*NotFound) orderCancelRes()  {}
func (*NotFound) orderPayRes()     {}

// NewOptOrderPayRequest returns new OptOrderPayRequest with value set to v.
func NewOptOrderPayRequest(v OrderPayRequest) OptOrderPayRequest {
	return OptOrderPayRequest{
		Value: v,
		Set:   true,
	}
}

// OptOrderPayRequest is optional OrderPayRequest.
type OptOrderPayRequest struct {
	Value OrderPayRequest
	Set   bool
}

// IsSet returns true if OptOrderPayRequest was set.
func (o OptOrderPayRequest) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptOrderPayRequest) Reset() {
	var v OrderPayRequest
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptOrderPayRequest) SetTo(v OrderPayRequest) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptOrderPayRequest) Get() (v OrderPayRequest, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptOrderPayRequest) Or(d OrderPayRequest) OrderPayRequest {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/order_cancel_response
type OrderCancelResponse struct {
	// Transaction Id.
	TransactionUUID string `json:"transaction_uuid"`
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *OrderCancelResponse) GetTransactionUUID() string {
	return s.TransactionUUID
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *OrderCancelResponse) SetTransactionUUID(val string) {
	s.TransactionUUID = val
}

func (*OrderCancelResponse) orderCancelRes() {}

// Ref: #/components/schemas/order_dto
type OrderDto struct {
	// Order ID.
	OrderUUID string `json:"order_uuid"`
	// User ID.
	UserUUID string `json:"user_uuid"`
	// Parts Id array.
	PartUuids []string `json:"part_uuids"`
	// Total price.
	TotalPrice float64 `json:"total_price"`
	// User ID.
	TransactionUUID string        `json:"transaction_uuid"`
	PaymentMethod   PaymentMethod `json:"payment_method"`
	Status          Status        `json:"status"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *OrderDto) GetOrderUUID() string {
	return s.OrderUUID
}

// GetUserUUID returns the value of UserUUID.
func (s *OrderDto) GetUserUUID() string {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *OrderDto) GetPartUuids() []string {
	return s.PartUuids
}

// GetTotalPrice returns the value of TotalPrice.
func (s *OrderDto) GetTotalPrice() float64 {
	return s.TotalPrice
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *OrderDto) GetTransactionUUID() string {
	return s.TransactionUUID
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *OrderDto) GetPaymentMethod() PaymentMethod {
	return s.PaymentMethod
}

// GetStatus returns the value of Status.
func (s *OrderDto) GetStatus() Status {
	return s.Status
}

// SetOrderUUID sets the value of OrderUUID.
func (s *OrderDto) SetOrderUUID(val string) {
	s.OrderUUID = val
}

// SetUserUUID sets the value of UserUUID.
func (s *OrderDto) SetUserUUID(val string) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *OrderDto) SetPartUuids(val []string) {
	s.PartUuids = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *OrderDto) SetTotalPrice(val float64) {
	s.TotalPrice = val
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *OrderDto) SetTransactionUUID(val string) {
	s.TransactionUUID = val
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *OrderDto) SetPaymentMethod(val PaymentMethod) {
	s.PaymentMethod = val
}

// SetStatus sets the value of Status.
func (s *OrderDto) SetStatus(val Status) {
	s.Status = val
}

func (*OrderDto) getOrderByIdRes() {}

// Ref: #/components/schemas/order_pay_request
type OrderPayRequest struct {
	PaymentMethod PaymentMethod `json:"payment_method"`
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *OrderPayRequest) GetPaymentMethod() PaymentMethod {
	return s.PaymentMethod
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *OrderPayRequest) SetPaymentMethod(val PaymentMethod) {
	s.PaymentMethod = val
}

// Ref: #/components/schemas/order_pay_response
type OrderPayResponse struct {
	// Transaction Id.
	TransactionUUID string `json:"transaction_uuid"`
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *OrderPayResponse) GetTransactionUUID() string {
	return s.TransactionUUID
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *OrderPayResponse) SetTransactionUUID(val string) {
	s.TransactionUUID = val
}

func (*OrderPayResponse) orderPayRes() {}

// Payment method.
// Ref: #/components/schemas/payment_method
type PaymentMethod string

const (
	PaymentMethodPAYMENTMETHODCARD        PaymentMethod = "PAYMENT_METHOD_CARD"
	PaymentMethodPAYMENTMETHODSBP         PaymentMethod = "PAYMENT_METHOD_SBP"
	PaymentMethodPAYMENTMETHODCREDITCARD  PaymentMethod = "PAYMENT_METHOD_CREDIT_CARD"
	PaymentMethodPAYMENTMETHODINVESTORMON PaymentMethod = "PAYMENT_METHOD_INVESTOR_MON"
)

// AllValues returns all PaymentMethod values.
func (PaymentMethod) AllValues() []PaymentMethod {
	return []PaymentMethod{
		PaymentMethodPAYMENTMETHODCARD,
		PaymentMethodPAYMENTMETHODSBP,
		PaymentMethodPAYMENTMETHODCREDITCARD,
		PaymentMethodPAYMENTMETHODINVESTORMON,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PaymentMethod) MarshalText() ([]byte, error) {
	switch s {
	case PaymentMethodPAYMENTMETHODCARD:
		return []byte(s), nil
	case PaymentMethodPAYMENTMETHODSBP:
		return []byte(s), nil
	case PaymentMethodPAYMENTMETHODCREDITCARD:
		return []byte(s), nil
	case PaymentMethodPAYMENTMETHODINVESTORMON:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PaymentMethod) UnmarshalText(data []byte) error {
	switch PaymentMethod(data) {
	case PaymentMethodPAYMENTMETHODCARD:
		*s = PaymentMethodPAYMENTMETHODCARD
		return nil
	case PaymentMethodPAYMENTMETHODSBP:
		*s = PaymentMethodPAYMENTMETHODSBP
		return nil
	case PaymentMethodPAYMENTMETHODCREDITCARD:
		*s = PaymentMethodPAYMENTMETHODCREDITCARD
		return nil
	case PaymentMethodPAYMENTMETHODINVESTORMON:
		*s = PaymentMethodPAYMENTMETHODINVESTORMON
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Order status.
// Ref: #/components/schemas/status
type Status string

const (
	StatusPAID           Status = "PAID"
	StatusPENDINGPAYMENT Status = "PENDING_PAYMENT"
	StatusCANCELLED      Status = "CANCELLED"
)

// AllValues returns all Status values.
func (Status) AllValues() []Status {
	return []Status{
		StatusPAID,
		StatusPENDINGPAYMENT,
		StatusCANCELLED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s Status) MarshalText() ([]byte, error) {
	switch s {
	case StatusPAID:
		return []byte(s), nil
	case StatusPENDINGPAYMENT:
		return []byte(s), nil
	case StatusCANCELLED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *Status) UnmarshalText(data []byte) error {
	switch Status(data) {
	case StatusPAID:
		*s = StatusPAID
		return nil
	case StatusPENDINGPAYMENT:
		*s = StatusPENDINGPAYMENT
		return nil
	case StatusCANCELLED:
		*s = StatusCANCELLED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
