// Code generated by ogen, DO NOT EDIT.

package orders_v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateNewOrder implements CreateNewOrder operation.
	//
	// Creates new order with selected details.
	//
	// POST /api/v1/orders
	CreateNewOrder(ctx context.Context, req *CreateOrderRequest) (*CreateOrderResponse, error)
	// GetOrderById implements GetOrderById operation.
	//
	// Get order by id.
	//
	// GET /api/v1/orders/{order_uuid}
	GetOrderById(ctx context.Context, params GetOrderByIdParams) (GetOrderByIdRes, error)
	// OrderCancel implements OrderCancel operation.
	//
	// Cancel order.
	//
	// POST /api/v1/orders/{order_uuid}/cancel
	OrderCancel(ctx context.Context, params OrderCancelParams) (OrderCancelRes, error)
	// OrderPay implements OrderPay operation.
	//
	// Request for order payment.
	//
	// POST /api/v1/orders/{order_uuid}/pay
	OrderPay(ctx context.Context, req OptOrderPayRequest, params OrderPayParams) (OrderPayRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
