// Code generated by ogen, DO NOT EDIT.

package orders_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateNewOrder implements CreateNewOrder operation.
//
// Creates new order with selected details.
//
// POST /api/v1/orders
func (UnimplementedHandler) CreateNewOrder(ctx context.Context, req *CreateOrderRequest) (r *CreateOrderResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrderById implements GetOrderById operation.
//
// Get order by id.
//
// GET /api/v1/orders/{order_uuid}
func (UnimplementedHandler) GetOrderById(ctx context.Context, params GetOrderByIdParams) (r GetOrderByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// OrderCancel implements OrderCancel operation.
//
// Cancel order.
//
// POST /api/v1/orders/{order_uuid}/cancel
func (UnimplementedHandler) OrderCancel(ctx context.Context, params OrderCancelParams) (r OrderCancelRes, _ error) {
	return r, ht.ErrNotImplemented
}

// OrderPay implements OrderPay operation.
//
// Request for order payment.
//
// POST /api/v1/orders/{order_uuid}/pay
func (UnimplementedHandler) OrderPay(ctx context.Context, req OptOrderPayRequest, params OrderPayParams) (r OrderPayRes, _ error) {
	return r, ht.ErrNotImplemented
}
