// Code generated by ogen, DO NOT EDIT.
package orders_v1

type GetOrderByIdRes interface {
	getOrderByIdRes()
}

type OrderCancelRes interface {
	orderCancelRes()
}

type OrderPayRes interface {
	orderPayRes()
}
