// Custom mockery prefix
// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/MoMentalochka/HomeWork/order/internal/model"
	orders_v1 "github.com/MoMentalochka/HomeWork/shared/pkg/openapi/order/v1"
	mock "github.com/stretchr/testify/mock"
)

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

type OrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderService) EXPECT() *OrderService_Expecter {
	return &OrderService_Expecter{mock: &_m.Mock}
}

// CreateNewOrder provides a mock function with given fields: ctx, req
func (_m *OrderService) CreateNewOrder(ctx context.Context, req model.CreateOrderRequest) (*orders_v1.CreateOrderResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateNewOrder")
	}

	var r0 *orders_v1.CreateOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateOrderRequest) (*orders_v1.CreateOrderResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateOrderRequest) *orders_v1.CreateOrderResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*orders_v1.CreateOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CreateOrderRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_CreateNewOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNewOrder'
type OrderService_CreateNewOrder_Call struct {
	*mock.Call
}

// CreateNewOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - req model.CreateOrderRequest
func (_e *OrderService_Expecter) CreateNewOrder(ctx interface{}, req interface{}) *OrderService_CreateNewOrder_Call {
	return &OrderService_CreateNewOrder_Call{Call: _e.mock.On("CreateNewOrder", ctx, req)}
}

func (_c *OrderService_CreateNewOrder_Call) Run(run func(ctx context.Context, req model.CreateOrderRequest)) *OrderService_CreateNewOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CreateOrderRequest))
	})
	return _c
}

func (_c *OrderService_CreateNewOrder_Call) Return(_a0 *orders_v1.CreateOrderResponse, _a1 error) *OrderService_CreateNewOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_CreateNewOrder_Call) RunAndReturn(run func(context.Context, model.CreateOrderRequest) (*orders_v1.CreateOrderResponse, error)) *OrderService_CreateNewOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderById provides a mock function with given fields: _a0, uuid
func (_m *OrderService) GetOrderById(_a0 context.Context, uuid string) (*model.OrderDto, error) {
	ret := _m.Called(_a0, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderById")
	}

	var r0 *model.OrderDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.OrderDto, error)); ok {
		return rf(_a0, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.OrderDto); ok {
		r0 = rf(_a0, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OrderDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_GetOrderById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderById'
type OrderService_GetOrderById_Call struct {
	*mock.Call
}

// GetOrderById is a helper method to define mock.On call
//   - _a0 context.Context
//   - uuid string
func (_e *OrderService_Expecter) GetOrderById(_a0 interface{}, uuid interface{}) *OrderService_GetOrderById_Call {
	return &OrderService_GetOrderById_Call{Call: _e.mock.On("GetOrderById", _a0, uuid)}
}

func (_c *OrderService_GetOrderById_Call) Run(run func(_a0 context.Context, uuid string)) *OrderService_GetOrderById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderService_GetOrderById_Call) Return(_a0 *model.OrderDto, _a1 error) *OrderService_GetOrderById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_GetOrderById_Call) RunAndReturn(run func(context.Context, string) (*model.OrderDto, error)) *OrderService_GetOrderById_Call {
	_c.Call.Return(run)
	return _c
}

// OrderCancel provides a mock function with given fields: _a0, uuid
func (_m *OrderService) OrderCancel(_a0 context.Context, uuid string) (orders_v1.OrderCancelRes, error) {
	ret := _m.Called(_a0, uuid)

	if len(ret) == 0 {
		panic("no return value specified for OrderCancel")
	}

	var r0 orders_v1.OrderCancelRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (orders_v1.OrderCancelRes, error)); ok {
		return rf(_a0, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) orders_v1.OrderCancelRes); ok {
		r0 = rf(_a0, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(orders_v1.OrderCancelRes)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_OrderCancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrderCancel'
type OrderService_OrderCancel_Call struct {
	*mock.Call
}

// OrderCancel is a helper method to define mock.On call
//   - _a0 context.Context
//   - uuid string
func (_e *OrderService_Expecter) OrderCancel(_a0 interface{}, uuid interface{}) *OrderService_OrderCancel_Call {
	return &OrderService_OrderCancel_Call{Call: _e.mock.On("OrderCancel", _a0, uuid)}
}

func (_c *OrderService_OrderCancel_Call) Run(run func(_a0 context.Context, uuid string)) *OrderService_OrderCancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderService_OrderCancel_Call) Return(_a0 orders_v1.OrderCancelRes, _a1 error) *OrderService_OrderCancel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_OrderCancel_Call) RunAndReturn(run func(context.Context, string) (orders_v1.OrderCancelRes, error)) *OrderService_OrderCancel_Call {
	_c.Call.Return(run)
	return _c
}

// OrderPay provides a mock function with given fields: ctx, method, uuid
func (_m *OrderService) OrderPay(ctx context.Context, method orders_v1.OptOrderPayRequest, uuid string) (orders_v1.OrderPayRes, error) {
	ret := _m.Called(ctx, method, uuid)

	if len(ret) == 0 {
		panic("no return value specified for OrderPay")
	}

	var r0 orders_v1.OrderPayRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, orders_v1.OptOrderPayRequest, string) (orders_v1.OrderPayRes, error)); ok {
		return rf(ctx, method, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, orders_v1.OptOrderPayRequest, string) orders_v1.OrderPayRes); ok {
		r0 = rf(ctx, method, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(orders_v1.OrderPayRes)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, orders_v1.OptOrderPayRequest, string) error); ok {
		r1 = rf(ctx, method, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_OrderPay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrderPay'
type OrderService_OrderPay_Call struct {
	*mock.Call
}

// OrderPay is a helper method to define mock.On call
//   - ctx context.Context
//   - method orders_v1.OptOrderPayRequest
//   - uuid string
func (_e *OrderService_Expecter) OrderPay(ctx interface{}, method interface{}, uuid interface{}) *OrderService_OrderPay_Call {
	return &OrderService_OrderPay_Call{Call: _e.mock.On("OrderPay", ctx, method, uuid)}
}

func (_c *OrderService_OrderPay_Call) Run(run func(ctx context.Context, method orders_v1.OptOrderPayRequest, uuid string)) *OrderService_OrderPay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(orders_v1.OptOrderPayRequest), args[2].(string))
	})
	return _c
}

func (_c *OrderService_OrderPay_Call) Return(_a0 orders_v1.OrderPayRes, _a1 error) *OrderService_OrderPay_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_OrderPay_Call) RunAndReturn(run func(context.Context, orders_v1.OptOrderPayRequest, string) (orders_v1.OrderPayRes, error)) *OrderService_OrderPay_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
